- alias: 'Flight entry notification'
  trigger:
    platform: event
    event_type: opensky_entry
  action:
    service: notify.jw
    data_template:
        message : 'Flight entry of {{ trigger.event.data.callsign }} '