- alias: Basement door open
  trigger:
    platform: state
    entity_id: binary_sensor.door_window_sensor_158d0001b7aa08
    from: 'off'
    to: 'on'
  action:
    service: light.turn_on
    entity_id: light.basement

- alias: Basement door closed
  trigger:
    platform: state
    entity_id: binary_sensor.door_window_sensor_158d0001b7aa08
    from: 'on'
    to: 'off'
  action:
    service: light.turn_off
    entity_id: light.basement