- alias: End the day
  trigger:
    - platform: event
      event_type: click
      event_data:
        entity_id: binary_sensor.switch_158d0001e88672
        click_type: single
  action:
      service: notify.jw
      data:
        message: "test message with switch"